<?php

namespace Database\Seeders\Prep;

use App\Models\Tag;
use App\Models\TagType;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TagSeeder extends Seeder
{
    public function run(): void
    {
        $tagTypes = TagType::all();


        $topicType = $tagTypes->where('slug', 'topics')->first();

        if ($topicType) {
            $topicType->tags()->createMany([
                ["name" => ["en" => "Data Analysis", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Data Management", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Data Visualisation", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Options by Context", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Sampling", "es" => "Muestreo", "fr" => ""]],
                ["name" => ["en" => "Study Design", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Estimation", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Surveys", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Indicators", "es" => "Indicadores", "fr" => ""]],
                ["name" => ["en" => "Questionnaire Design", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Typology", "es" => "Tipologías", "fr" => ""]],
                ["name" => ["en" => "ODK", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Food Security", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Farm Productivity", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Participatory Research", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Report Writing", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Right-N", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Data Collection", "es" => "", "fr" => ""]],
                ["name" => ["en" => "IT Infrastructure", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Data Storage", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Interview Technique", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Dataverse", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Academia", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Baseline", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Endline", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Sampling Weights", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Research Quality", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Diet", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Nutrition", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Experiment Design", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Data Management Plan", "es" => "", "fr" => ""]],
                ["name" => ["en" => "R Instat", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Qualitative Data", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Local Knowledge", "es" => "Conocimientos Tradicionales", "fr" => ""]],
                ["name" => ["en" => "Metadata", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Text Analysis", "es" => "Analisis de texto", "fr" => ""]],
                ["name" => ["en" => "RQDA", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Agroforestry", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Intercropping", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Land Use", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Livestock", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Pest Management", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Integrated Pest Management (IPM)"]],
                ["name" => ["en" => "Evaluation", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Principle Components Analysis", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Fall Army Worm \/ Spodoptera"]],
                ["name" => ["en" => "Farmer Training", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Activism", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Gender Equality", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Development", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Stakeholder Analysis", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Monitoring and Evaluation", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Agricultural Development", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Gender Analysis", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Weather Forecasting", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Technology Transfer", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Soil Fertility", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Crop Management", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Aflatoxin", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Grain Drying", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Post-harvest handling", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Farmer Analysis", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Climate Change", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Ecology", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Striga", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Variety Trials", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Shiny", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Apps", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Data Quality", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Agronomy", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Research Protocol", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Agriculture", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Inferential Statistics", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Hypothesis Testing", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Significance", "es" => "", "fr" => ""]],
                ["name" => ["en" => "ANOVA", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Mixed models", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Data Structures", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Generalised Linear Models", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Databases", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Mixed Methods", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Quantitative Data", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Variability", "es" => "Variabilidad", "fr" => ""]],
                ["name" => ["en" => "Fieldwork", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Ethics", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Multi-stage Sampling", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Phone surveys", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Pilot-testing", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Online surveys", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Measurement", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Quality Assurance"]],
                ["name" => ["en" => "CSPro"]],
                ["name" => ["en" => "Open Data"]],
                ["name" => ["en" => "Data Repository"]],
                ["name" => ["en" => "Ranking & Scoring \/ Rating"]],
                ["name" => ["en" => "Agroecological Transitions"]],
                ["name" => ["en" => "Social Network Analysis"]],
                ["name" => ["en" => "Advocacy"]],
            ]);
        }

        $keywordType = $tagTypes->where('slug', 'keywords')->first();

        if ($keywordType) {
            $keywordType->tags()->createMany([
                ["name" => ["en" => "Programming", "es" => "", "fr" => ""]],
                ["name" => ["en" => "UNHCR"]],
                ["name" => ["en" => "Harmonisation", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Standardisation", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Household", "es" => "", "fr" => ""]],
                ["name" => ["en" => "HDDS", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Communication", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Systems Approach", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Rhomis", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Iodine", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Principles", "es" => "Principios", "fr" => "Principes"]],
                ["name" => ["en" => "ES", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Behaviour Change", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Adoption", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Innovation", "es" => "", "fr" => ""]],
                ["name" => ["en" => "BRCiS", "es" => "", "fr" => ""]],
                ["name" => ["en" => "CGIAR", "es" => "", "fr" => ""]],
                ["name" => ["en" => "CRP", "es" => "", "fr" => ""]],
                ["name" => ["en" => "CCAFS", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Empowerment", "es" => "Empoderamiento", "fr" => ""]],
                ["name" => ["en" => "Cultural Values", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Methodology", "es" => "", "fr" => ""]],
                ["name" => ["en" => "AEI for review", "es" => "", "fr" => ""]],
                ["name" => ["en" => "ASB", "es" => "", "fr" => ""]],
                ["name" => ["en" => "DASS", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Norad", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Biochar", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Enclosure", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Agroecological Intensification", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Agro-pastoralism", "es" => "", "fr" => ""]],
                ["name" => ["en" => "ICRAF", "es" => "", "fr" => ""]],
                ["name" => ["en" => "DFID", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Feminism", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Power Analysis", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Humidtropics", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Networks", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Nonprofit strategy", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Foundation Strategy", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Nonprofit Networks", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Collaboration", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Local Indicators", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Agrodiversity", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Value Chain Development", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Biocultural Diversity", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Agrobiodiversity", "es" => "", "fr" => ""]],
                ["name" => ["en" => "rdrop2", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Ownership", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Dashboard", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Maize", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Research for Development", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Zotero", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Theory of Change", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Transdisciplinary Approaches", "es" => "", "fr" => ""]],
                ["name" => ["en" => "CIAT", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Grains", "es" => "", "fr" => ""]],
                ["name" => ["en" => "McKnight", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Framework", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Genstat", "es" => "", "fr" => ""]],
                ["name" => ["en" => "MSTAT", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Excel", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Seed Systems", "es" => "Sistemas de Semillas", "fr" => ""]],
                ["name" => ["en" => "CLACSO", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Graphs", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Population", "es" => "Poblacion", "fr" => ""]],
                ["name" => ["en" => "Participatory Action Research", "es" => "Investigación Acción Participativa", "fr" => ""]],
                ["name" => ["en" => "EN", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Observations", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Photos", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Reverse Order", "es" => "", "fr" => ""]],
                ["name" => ["en" => "DHS", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Fertility", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Mortality", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Literature Review", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Multi-Environment Trials"]],
                ["name" => ["en" => "e-learning"]],
                ["name" => ["en" => "Replication"]],
                ["name" => ["en" => "Blocks"]],
                ["name" => ["en" => "Charts"]],
                ["name" => ["en" => "Graphics"]],
                ["name" => ["en" => "R Commands"]],
                ["name" => ["en" => "Agriculture"]],
                ["name" => ["en" => "On-station"]],
                ["name" => ["en" => "Sample Size"]],
                ["name" => ["en" => "Representative Sample"]],
                ["name" => ["en" => "Research Data"]],
                ["name" => ["en" => "NERC"]],
                ["name" => ["en" => "Data Centres"]],
                ["name" => ["en" => "Policy-Making"]],
                ["name" => ["en" => "Business"]],
                ["name" => ["en" => "Household Survey"]],
                ["name" => ["en" => "Measurement"]],
                ["name" => ["en" => "Farm Size"]],
                ["name" => ["en" => "Research Paper"]],
                ["name" => ["en" => "On-Farm"]],
                ["name" => ["en" => "Objectives"]],
                ["name" => ["en" => "Drylands"]],
                ["name" => ["en" => "Interview"]],
                ["name" => ["en" => "Enumerators"]],
                ["name" => ["en" => "Supervisors"]],
                ["name" => ["en" => "Dataverse"]],
                ["name" => ["en" => "Archiving"]],
                ["name" => ["en" => "Data sharing"]],
                ["name" => ["en" => "XLSForm"]],
                ["name" => ["en" => "Data Modelling"]],
                ["name" => ["en" => "R Packages"]],
                ["name" => ["en" => "GGplot2"]],
                ["name" => ["en" => "UNICEF"]],
                ["name" => ["en" => "heterogeneity"]],
                ["name" => ["en" => "risk"]],
                ["name" => ["en" => "technology"]],
                ["name" => ["en" => "Smallholder farmers"]],
                ["name" => ["en" => "translation"]],
                ["name" => ["en" => "Stats4SD"]],
                ["name" => ["en" => "Organogram"]],
                ["name" => ["en" => "data ownership"]],
                ["name" => ["en" => "IP rights"]],
                ["name" => ["en" => "data archiving"]],
                ["name" => ["en" => "confidential data"]],
                ["name" => ["en" => "PII"]],
                ["name" => ["en" => "prior informed consent"]],
                ["name" => ["en" => "Dublin Core"]],
                ["name" => ["en" => "Codebook"]],
                ["name" => ["en" => "data cleaning"]],
                ["name" => ["en" => "Statistics"]],
                ["name" => ["en" => "Satellite data"]],
                ["name" => ["en" => "climatic data"]],
                ["name" => ["en" => "outcomes"]],
                ["name" => ["en" => "results - based management(RBM)"]],
                ["name" => ["en" => "social movement"]],
                ["name" => ["en" => "research process"]],
                ["name" => ["en" => "RMS"]],
                ["name" => ["en" => "DDS"]],
                ["name" => ["en" => "Impact Measurement"]],
                ["name" => ["en" => "Sustainability Assessment"]],
                ["name" => ["en" => "Multi Criteria Decision Analysis"]],
                ["name" => ["en" => "Covid - 19"]],
                ["name" => ["en" => "Agricultural techniques"]],
                ["name" => ["en" => "Crop rotation"]],
                ["name" => ["en" => "sorghum"]],
                ["name" => ["en" => "pearl millet"]],
                ["name" => ["en" => "Field notes"]],
                ["name" => ["en" => "Data loop"]],
                ["name" => ["en" => "Blocking"]],
                ["name" => ["en" => "social science"]],
                ["name" => ["en" => "social research"]],
                ["name" => ["en" => "Focus Group Discussion"]],
                ["name" => ["en" => "Trials"]],
                ["name" => ["en" => "Factor Analysis"]],
                ["name" => ["en" => "acculturation"]],
                ["name" => ["en" => "ecology"]],
                ["name" => ["en" => "validity"]],
                ["name" => ["en" => "credibility"]],
                ["name" => ["en" => "WorldFIsh"]],
                ["name" => ["en" => "power"]],
                ["name" => ["en" => "Data Infographic"]],
                ["name" => ["en" => "Photography in Fieldwork"]],
                ["name" => ["en" => "Ethical Photography"]],
                ["name" => ["en" => "Sorgho"]],
                ["name" => ["en" => "Mil"]],
                ["name" => ["en" => "Sorgh"]],
                ["name" => ["en" => "r"]],
                ["name" => ["en" => "rstudio"]],
                ["name" => ["en" => "data visualisation"]],
                ["name" => ["en" => "plot"]],
                ["name" => ["en" => "graph"]],
                ["name" => ["en" => "USAID"]],
                ["name" => ["en" => "Gender"]],
                ["name" => ["en" => "Gender Differences"]],
                ["name" => ["en" => "Gender in Research"]],
                ["name" => ["en" => "Gender Issues"]],
                ["name" => ["en" => "Factsheet"]],
                ["name" => ["en" => "Gender Inequality"]],
                ["name" => ["en" => "Focus Group Discussions"]],
                ["name" => ["en" => "Propensity Score Matching"]],
                ["name" => ["en" => "Women Farmers"]],
                ["name" => ["en" => "Gender Gap"]],
                ["name" => ["en" => "Gender in Farming"]],
                ["name" => ["en" => "Gender in Agriculture"]],
                ["name" => ["en" => "Gender Training Tools"]],
                ["name" => ["en" => "Agriculture Index"]],
                ["name" => ["en" => "Inclusion of Women"]],
                ["name" => ["en" => "Women\u2019s Empowerment"]],
                ["name" => ["en" => "Data Handling"]],
                ["name" => ["en" => "Data Protection"]],
                ["name" => ["en" => "Research Project"]],
                ["name" => ["en" => "Copyrighting"]],
                ["name" => ["en" => "Data Copyright"]],
                ["name" => ["en" => "Data Organisation"]],
                ["name" => ["en" => "Data Manager"]],
                ["name" => ["en" => "constraints"]],
                ["name" => ["en" => "skip patterns"]],
                ["name" => ["en" => "relevancies"]],
                ["name" => ["en" => "small farmer"]],
                ["name" => ["en" => "ODK Aggregators"]],
                ["name" => ["en" => "Kobo"]],
                ["name" => ["en" => "Kobotoolbox"]],
                ["name" => ["en" => "Digital Data Collection"]],
                ["name" => ["en" => "ODK Collect"]],
                ["name" => ["en" => "Influence Diagrams"]],
                ["name" => ["en" => "dplyr"]],
                ["name" => ["en" => "data"]],
                ["name" => ["en" => "video"]],
                ["name" => ["en" => "introduction"]],
                ["name" => ["en" => "ODK"]],
                ["name" => ["en" => "Sampling"]],
                ["name" => ["en" => "Estimation"]],
                ["name" => ["en" => "Random Sample"]],
                ["name" => ["en" => "Cross - Tabulation"]],
                ["name" => ["en" => "Coding"]],
                ["name" => ["en" => "Multiple Resonse Data"]],
                ["name" => ["en" => "Indicators"]],
                ["name" => ["en" => "Soil Management"]],
                ["name" => ["en" => "Soil Tool Kit"]],
                ["name" => ["en" => "Data Platform"]],
                ["name" => ["en" => "Millet"]],
                ["name" => ["en" => "Sweet Potato"]],
                ["name" => ["en" => "Cassava"]],
                ["name" => ["en" => "Domain analysis"]],
                ["name" => ["en" => "System dynamics"]],
                ["name" => ["en" => "Problem Solving"]],
                ["name" => ["en" => "NRI"]],
                ["name" => ["en" => "Assessment"]],
                ["name" => ["en" => "Support"]],
                ["name" => ["en" => "Time series"]],
                ["name" => ["en" => "Virtual meeting"]],
                ["name" => ["en" => "Facilitation"]],
                ["name" => ["en" => "Webinar"]],
                ["name" => ["en" => "configuration"]],
                ["name" => ["en" => "tidyverse"]],
                ["name" => ["en" => "rmd"]],
                ["name" => ["en" => "project"]],
                ["name" => ["en" => "test"]],
                ["name" => ["en" => "analysis"]],
                ["name" => ["en" => "t test"]],
                ["name" => ["en" => "wilcox"]],
                ["name" => ["en" => "analysis workflow"]],
                ["name" => ["en" => "chi square"]],
                ["name" => ["en" => "facets"]],
                ["name" => ["en" => "data management"]],
                ["name" => ["en" => "data manipulation"]],
                ["name" => ["en" => "pipe"]],
                ["name" => ["en" => "data analysis"]],
                ["name" => ["en" => "lm"]],
                ["name" => ["en" => "broom"]],
                ["name" => ["en" => "MCDA"]],
                ["name" => ["en" => "factors"]],
                ["name" => ["en" => "interactions"]],
                ["name" => ["en" => "plots"]],
                ["name" => ["en" => "Research Questions"]],
                ["name" => ["en" => "Internal Validity"]],
                ["name" => ["en" => "External Validity"]],
                ["name" => ["en" => "ona"]],
                ["name" => ["en" => "Posters"]],
                ["name" => ["en" => "Conferences"]],
                ["name" => ["en" => "Presentations"]],
                ["name" => ["en" => "Academic Writing"]],
                ["name" => ["en" => "Precision"]],
                ["name" => ["en" => "Tables"]],
                ["name" => ["en" => "Map"]],
                ["name" => ["en" => "Maps"]],
                ["name" => ["en" => "Workshop"]],
                ["name" => ["en" => "Agroecological principles"]],
                ["name" => ["en" => "Local values"]],
                ["name" => ["en" => "CCRP"]],
                ["name" => ["en" => "Causal diagrams"]],
                ["name" => ["en" => "Research Methods"]],
                ["name" => ["en" => "Playlist"]],
                ["name" => ["en" => "overview"]],
                ["name" => ["en" => "FRN"]],
                ["name" => ["en" => "protocol"]],
                ["name" => ["en" => "Social Network Analysis"]],
                ["name" => ["en" => "GIZ"]],
                ["name" => ["en" => "Survey"]],
                ["name" => ["en" => "error"]],
                ["name" => ["en" => "soil health"]],
                ["name" => ["en" => "logistic modelling"]],
                ["name" => ["en" => "regression"]],
                ["name" => ["en" => "hypothesis testing"]],
                ["name" => ["en" => "linear modelling"]],
                ["name" => ["en" => "markdown"]],
                ["name" => ["en" => "data shapes"]],
                ["name" => ["en" => "relational data"]],
                ["name" => ["en" => "merging data"]],
                ["name" => ["en" => "Observation"]],
                ["name" => ["en" => "Social media"]],
                ["name" => ["en" => "Dissemination"]],
                ["name" => ["en" => "Capacity development"]],
                ["name" => ["en" => "Demonstration farms"]],
                ["name" => ["en" => "demonstration farms"]],
                ["name" => ["en" => "rapid studies"]],
                ["name" => ["en" => "rapid experiments"]],
                ["name" => ["en" => "Social Capital"]],
                ["name" => ["en" => "Impact Evaluation"]],
                ["name" => ["en" => "return and Reintegration"]],
                ["name" => ["en" => "Randomised Controlled Trials"]],
                ["name" => ["en" => "Advocacy"]],
                ["name" => ["en" => "Evidence"]],
                ["name" => ["en" => "experimental designs"]],
                ["name" => ["en" => "quasi - experimental designs"]],
                ["name" => ["en" => "natural experiments"]],
                ["name" => ["en" => "data flow"]],
                ["name" => ["en" => "transcription"]],
                ["name" => ["en" => "R"]],
                ["name" => ["en" => "reporting"]],
                ["name" => ["en" => "Researcher"]],
                ["name" => ["en" => "Career advice"]],
            ]);
        }

        $themeType = $tagTypes->where('slug', 'themes')->first();

        if ($themeType) {
            $themeType->tags()->createMany([
                ["name" => ["en" => "RM - Analysis", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Farmer Research Network"]],
                ["name" => ["en" => "Agroecology", "es" => "Agroecologia", "fr" => "Agroecologie"]],
                ["name" => ["en" => "RM - Design", "es" => "", "fr" => ""]],
                ["name" => ["en" => "RM - Data Collection and Management"]],
                ["name" => ["en" => "RM - Reporting"]],
                ["name" => ["en" => "RM - Ethics"]],
                ["name" => ["en" => "Society and Equity"]],
                ["name" => ["en" => "M & E"]],
            ]);
        }

        $resourceType = $tagTypes->where('slug', 'resource-types')->first();

        if ($resourceType) {
            $resourceType->tags()->createMany([
                ["name" => ["en" => "Video", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Organisational Diagram", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Webinar", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Meeting Recording", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Guide", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Case Study", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Journal Article", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Presentation", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Picture", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Diagram", "es" => "", "fr" => ""]],
                ["name" => ["en" => "XLS-form", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Survey", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Checklist", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Infographic", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Curricula / Training Course", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Reference", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Textbook", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Template", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Script", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Activity", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Leaflet", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Poster", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Example"]],
                ["name" => ["en" => "Tool"]],
                ["name" => ["en" => "App"]],
                ["name" => ["en" => "Questionnaire"]],
                ["name" => ["en" => "Booklet"]],
                ["name" => ["en" => "Report"]],
                ["name" => ["en" => "list of Resources"]],
                ["name" => ["en" => "Book"]],
                ["name" => ["en" => "Manual"]],
                ["name" => ["en" => "Website"]],
            ]);
        }


        $audienceType = $tagTypes->where('slug', 'audiences')->first();

        if ($audienceType) {
            $audienceType->tags()->createMany([
                ["name" => ["en" => "CCRP", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Stats4SD Internal", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Children", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Researchers", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Students", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Farmers", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Policy - Makers"]],
            ]);
        }

        $locationType = $tagTypes->where('slug', 'locations')->first();

        if ($locationType) {
            $locationType->tags()->createMany([
                ["name" => ["en" => "Andes", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Africa", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Kenya", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Burkina Faso", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Bolivia", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Zimbabwe", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Mexico", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Malawi", "es" => "", "fr" => ""]],
                ["name" => ["en" => "East Africa", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Tanzania", "es" => "", "fr" => ""]],
                ["name" => ["en" => "West Africa"]],
                ["name" => ["en" => "Nigeria"]],
                ["name" => ["en" => "Ecuador"]],
                ["name" => ["en" => "United Kingdom"]],
                ["name" => ["en" => "Denmark"]],
                ["name" => ["en" => "Niger"]],
                ["name" => ["en" => "Zambia"]],
                ["name" => ["en" => "Uganda"]],
                ["name" => ["en" => "Peru"]],
                ["name" => ["en" => "China"]],
                ["name" => ["en" => "Panama"]],
                ["name" => ["en" => "India"]],
                ["name" => ["en" => "Mali"]],
                ["name" => ["en" => "Bangladesh"]],
                ["name" => ["en" => "Guatemala"]],
            ]);
        }

        $authorType = $tagTypes->where('slug', 'authors')->first();

        if ($authorType) {
            $authorType->tags()->createMany([

                ["name" => ["en" => "IFAD", "es" => "IFAD", "fr" => "IFAD"]],
                ["name" => ["en" => "UNICEF", "es" => "", "fr" => ""]],
                ["name" => ["en" => "CIDSE", "es" => "", "fr" => ""]],
                ["name" => ["en" => "Stephen R. Gliessman", "es" => "Stephen R. Gliessman", "fr" => "Stephen R. Gliessman"]],
                ["name" => ["en" => "SIDA", "es" => "SIDA", "fr" => "SIDA"]],
                ["name" => ["en" => "GEO", "es" => "GEO", "fr" => "GEO"]],
                ["name" => ["en" => "Sam Dumble"]],
                ["name" => ["en" => "Douglas Gollin"]],
                ["name" => ["en" => "Alastair Orr", "es" => "Alastair Orr", "fr" => "Alastair Orr"]],
                ["name" => ["en" => "Aboubacar Toure", "es" => "Aboubacar Toure", "fr" => "Aboubacar Toure"]],
                ["name" => ["en" => "Access Agriculture", "es" => "Access Agriculture", "fr" => "Access Agriculture"]],
                ["name" => ["en" => "ACDI - VOCA", "es" => "ACDI - VOCA", "fr" => "ACDI - VOCA"]],
                ["name" => ["en" => "Agnes Quisumbing", "es" => "Agnes Quisumbing", "fr" => "Agnes Quisumbing"]],
                ["name" => ["en" => "Aichi Kitalyi", "es" => "Aichi Kitalyi", "fr" => "Aichi Kitalyi"]],
                ["name" => ["en" => "Alejandro Bonifacio", "es" => "Alejandro Bonifacio", "fr" => "Alejandro Bonifacio"]],
                ["name" => ["en" => "Alex Borda", "es" => "Alex Borda", "fr" => "Alex Borda"]],
                ["name" => ["en" => "Alex Riba", "es" => "Alex Riba", "fr" => "Alex Riba"]],
                ["name" => ["en" => "Alex Thomson", "es" => "Alex Thomson", "fr" => "Alex Thomson"]],
                ["name" => ["en" => "Ali Maman Aminou", "es" => "Ali Maman Aminou", "fr" => "Ali Maman Aminou"]],
                ["name" => ["en" => "Allan Hruska", "es" => "Allan Hruska", "fr" => "Allan Hruska"]],
                ["name" => ["en" => "Alphonce Musili", "es" => "Alphonce Musili", "fr" => "Alphonce Musili"]],
                ["name" => ["en" => "Amber Peterman", "es" => "Amber Peterman", "fr" => "Amber Peterman"]],
                ["name" => ["en" => "Amos Wekesa", "es" => "Amos Wekesa", "fr" => "Amos Wekesa"]],
                ["name" => ["en" => "AN Wekesa e", "es" => "AN Wekesa e", "fr" => "AN Wekesa e"]],
                ["name" => ["en" => "Ana Deaconu", "es" => "Ana Deaconu", "fr" => "Ana Deaconu"]],
                ["name" => ["en" => "Ana Vaz", "es" => "Ana Vaz", "fr" => "Ana Vaz"]],
                ["name" => ["en" => "Anders Malmer", "es" => "Anders Malmer", "fr" => "Anders Malmer"]],
                ["name" => ["en" => "André Koné", "es" => "André Koné", "fr" => "André Koné"]],
                ["name" => ["en" => "Andrew Pinney", "es" => "Andrew Pinney", "fr" => "Andrew Pinney"]],
                ["name" => ["en" => "Angela Mkindi", "es" => "Angela Mkindi", "fr" => "Angela Mkindi"]],
                ["name" => ["en" => "Anja Gassner", "es" => "Anja Gassner", "fr" => "Anja Gassner"]],
                ["name" => ["en" => "Parveen Anjarwalla", "es" => "Parveen Anjarwalla", "fr" => "Parveen Anjarwalla"]],
                ["name" => ["en" => "Philip Stevenson", "es" => "Philip Stevenson", "fr" => "Philip Stevenson"]],
                ["name" => ["en" => "Phosiso Sola", "es" => "Phosiso Sola", "fr" => "Phosiso Sola"]],
                ["name" => ["en" => "Ramni Jamnadass", "es" => "Ramni Jamnadass", "fr" => "Ramni Jamnadass"]],
                ["name" => ["en" => "Steven Belmain", "es" => "Steven Belmain", "fr" => "Steven Belmain"]],
                ["name" => ["en" => "Antonia Grönvall", "es" => "Antonia Grönvall", "fr" => "Antonia Grönvall"]],
                ["name" => ["en" => "Arathi Rao", "es" => "Arathi Rao", "fr" => "Arathi Rao"]],
                ["name" => ["en" => "Arouna Sangaré", "es" => "Arouna Sangaré", "fr" => "Arouna Sangaré"]],
                ["name" => ["en" => "ASB", "es" => "ASB", "fr" => "ASB"]],
                ["name" => ["en" => "Boddupalli Maruthi Prasanna", "es" => "Boddupalli Maruthi Prasanna", "fr" => "Boddupalli Maruthi Prasanna"]],
                ["name" => ["en" => "Edmundo Barrios", "es" => "Edmundo Barrios", "fr" => "Edmundo Barrios"]],
                ["name" => ["en" => "Peter Mortimer", "es" => "Peter Mortimer", "fr" => "Peter Mortimer"]],
                ["name" => ["en" => "Beria Leimona", "es" => "Beria Leimona", "fr" => "Beria Leimona"]],
                ["name" => ["en" => "Bernard Vanlauwe", "es" => "Bernard Vanlauwe", "fr" => "Bernard Vanlauwe"]],
                ["name" => ["en" => "Biovision", "es" => "Biovision", "fr" => "Biovision"]],
                ["name" => ["en" => "Blessing Magonziwa", "es" => "Blessing Magonziwa", "fr" => "Blessing Magonziwa"]],
                ["name" => ["en" => "Bocar Diallo", "es" => "Bocar Diallo", "fr" => "Bocar Diallo"]],
                ["name" => ["en" => "Carlos Barahona", "es" => "Carlos Barahona", "fr" => "Carlos Barahona"]],
                ["name" => ["en" => "Cathy Garlick", "es" => "Cathy Garlick", "fr" => "Cathy Garlick"]],
                ["name" => ["en" => "CCAFS", "es" => "CCAFS", "fr" => "CCAFS"]],
                ["name" => ["en" => "CCRP", "es" => "CCRP", "fr" => "CCRP"]],
                ["name" => ["en" => "CCRS", "es" => "CCRS", "fr" => "CCRS"]],
                ["name" => ["en" => "Cecilia Rocha", "es" => "Cecilia Rocha", "fr" => "Cecilia Rocha"]],
                ["name" => ["en" => "Center for Research Quality", "es" => "Center for Research Quality", "fr" => "Center for Research Quality"]],
                ["name" => ["en" => "CETRAD", "es" => "CETRAD", "fr" => "CETRAD"]],
                ["name" => ["en" => "CGiAR", "es" => "CGiAR", "fr" => "CGiAR"]],
                ["name" => ["en" => "Cheryl Dietrich", "es" => "Cheryl Dietrich", "fr" => "Cheryl Dietrich"]],
                ["name" => ["en" => "Chris Clarke", "es" => "Chris Clarke", "fr" => "Chris Clarke"]],
                ["name" => ["en" => "Christine Laetitia", "es" => "Christine Laetitia", "fr" => "Christine Laetitia"]],
                ["name" => ["en" => "CIDSE", "es" => "CIDSE", "fr" => "CIDSE"]],
                ["name" => ["en" => "CIDT", "es" => "CIDT", "fr" => "CIDT"]],
                ["name" => ["en" => "CIMMYT", "es" => "CIMMYT", "fr" => "CIMMYT"]],
                ["name" => ["en" => "Cindy Clark", "es" => "Cindy Clark", "fr" => "Cindy Clark"]],
                ["name" => ["en" => "Claire Nicklin", "es" => "Claire Nicklin", "fr" => "Claire Nicklin"]],
                ["name" => ["en" => "Colorado State University", "es" => "Colorado State University", "fr" => "Colorado State University"]],
                ["name" => ["en" => "Corinne Valdivia", "es" => "Corinne Valdivia", "fr" => "Corinne Valdivia"]],
                ["name" => ["en" => "D Wulandari", "es" => "D Wulandari", "fr" => "D Wulandari"]],
                ["name" => ["en" => "D . Carolina Quintero", "es" => "D . Carolina Quintero", "fr" => "D . Carolina Quintero"]],
                ["name" => ["en" => "Daimon Kambewa", "es" => "Daimon Kambewa", "fr" => "Daimon Kambewa"]],
                ["name" => ["en" => "Dam Viet Bac", "es" => "Dam Viet Bac", "fr" => "Dam Viet Bac"]],
                ["name" => ["en" => "Daniel Buckles", "es" => "Daniel Buckles", "fr" => "Daniel Buckles"]],
                ["name" => ["en" => "Daniel Mugendi", "es" => "Daniel Mugendi", "fr" => "Daniel Mugendi"]],
                ["name" => ["en" => "Daniel Nyambok", "es" => "Daniel Nyambok", "fr" => "Daniel Nyambok"]],
                ["name" => ["en" => "Danny Parsons", "es" => "Danny Parsons", "fr" => "Danny Parsons"]],
                ["name" => ["en" => "Dave Mills", "es" => "Dave Mills", "fr" => "Dave Mills"]],
                ["name" => ["en" => "David Jakinda Otieno", "es" => "David Jakinda Otieno", "fr" => "David Jakinda Otieno"]],
                ["name" => ["en" => "David Stern", "es" => "David Stern", "fr" => "David Stern"]],
                ["name" => ["en" => "David Williams", "es" => "David Williams", "fr" => "David Williams"]],
                ["name" => ["en" => "Deborah Duveskog", "es" => "Deborah Duveskog", "fr" => "Deborah Duveskog"]],
                ["name" => ["en" => "Diana Santillán", "es" => "Diana Santillán", "fr" => "Diana Santillán"]],
                ["name" => ["en" => "Diana Scearce", "es" => "Diana Scearce", "fr" => "Diana Scearce"]],
                ["name" => ["en" => "Dietmar Stoian", "es" => "Dietmar Stoian", "fr" => "Dietmar Stoian"]],
                ["name" => ["en" => "Djénéba Diarra", "es" => "Djénéba Diarra", "fr" => "Djénéba Diarra"]],
                ["name" => ["en" => "Donna Mertens", "es" => "Donna Mertens", "fr" => "Donna Mertens"]],
                ["name" => ["en" => "Douglas Gollin", "es" => "Douglas Gollin", "fr" => "Douglas Gollin"]],
                ["name" => ["en" => "Douglas Horton", "es" => "Douglas Horton", "fr" => "Douglas Horton"]],
                ["name" => ["en" => "Agnes Mwangwela", "es" => "Agnes Mwangwela", "fr" => "Agnes Mwangwela"]],
                ["name" => ["en" => "Francis Muyekho", "es" => "Francis Muyekho", "fr" => "Francis Muyekho"]],
                ["name" => ["en" => "Dr K Otieno", "es" => "Dr K Otieno", "fr" => "Dr K Otieno"]],
                ["name" => ["en" => "Dr Matthias Magunda", "es" => "Dr Matthias Magunda", "fr" => "Dr Matthias Magunda"]],
                ["name" => ["en" => "DT Cheruiyot", "es" => "DT Cheruiyot", "fr" => "DT Cheruiyot"]],
                ["name" => ["en" => "Edina Kahembe", "es" => "Edina Kahembe", "fr" => "Edina Kahembe"]],
                ["name" => ["en" => "echo ", "es" => "echo ", "fr" => "echo "]],
                ["name" => ["en" => "Edmundo Barrios", "es" => "Edmundo Barrios", "fr" => "Edmundo Barrios"]],
                ["name" => ["en" => "Edwin Adenya", "es" => "Edwin Adenya", "fr" => "Edwin Adenya"]],
                ["name" => ["en" => "Edwin Mariscal", "es" => "Edwin Mariscal", "fr" => "Edwin Mariscal"]],
                ["name" => ["en" => "Edwin Yucra", "es" => "Edwin Yucra", "fr" => "Edwin Yucra"]],
                ["name" => ["en" => "Eleanor Allan", "es" => "Eleanor Allan", "fr" => "Eleanor Allan"]],
                ["name" => ["en" => "Eleodoro Baldiviezo", "es" => "Eleodoro Baldiviezo", "fr" => "Eleodoro Baldiviezo"]],
                ["name" => ["en" => "Elias Jika", "es" => "Elias Jika", "fr" => "Elias Jika"]],
                ["name" => ["en" => "Elias Ziwa", "es" => "Elias Ziwa", "fr" => "Elias Ziwa"]],
                ["name" => ["en" => "Eliseo Mamani", "es" => "Eliseo Mamani", "fr" => "Eliseo Mamani"]],
                ["name" => ["en" => "Elizabeth Dozois", "es" => "Elizabeth Dozois", "fr" => "Elizabeth Dozois"]],
                ["name" => ["en" => "Emebet Wuhib Mutungi", "es" => "Emebet Wuhib Mutungi", "fr" => "Emebet Wuhib Mutungi"]],
                ["name" => ["en" => "Emily Nevitt", "es" => "Emily Nevitt", "fr" => "Emily Nevitt"]],
                ["name" => ["en" => "Emma Burrow", "es" => "Emma Burrow", "fr" => "Emma Burrow"]],
                ["name" => ["en" => "Ernesto Mendez", "es" => "Ernesto Mendez", "fr" => "Ernesto Mendez"]],
                ["name" => ["en" => "Eusebius Mukhwana", "es" => "Eusebius Mukhwana", "fr" => "Eusebius Mukhwana"]],
                ["name" => ["en" => "Eva Weltzien", "es" => "Eva Weltzien", "fr" => "Eva Weltzien"]],
                ["name" => ["en" => "Claus Sørensen", "es" => "Claus Sørensen", "fr" => "Claus Sørensen"]],
                ["name" => ["en" => "Eddie Bokkers", "es" => "Eddie Bokkers", "fr" => "Eddie Bokkers"]],
                ["name" => ["en" => "Evelien de Olde", "es" => "Evelien de Olde", "fr" => "Evelien de Olde"]],
                ["name" => ["en" => "Frank Oudshoorn", "es" => "Frank Oudshoorn", "fr" => "Frank Oudshoorn"]],
                ["name" => ["en" => "Imke de Boer", "es" => "Imke de Boer", "fr" => "Imke de Boer"]],
                ["name" => ["en" => "Ewa Wredle", "es" => "Ewa Wredle", "fr" => "Ewa Wredle"]],
                ["name" => ["en" => "Florence Kiyimba", "es" => "Florence Kiyimba", "fr" => "Florence Kiyimba"]],
                ["name" => ["en" => "Amel Ghouila", "es" => "Amel Ghouila", "fr" => "Amel Ghouila"]],
                ["name" => ["en" => "Azza Ahmed", "es" => "Azza Ahmed", "fr" => "Azza Ahmed"]],
                ["name" => ["en" => "Faisal Fadlelmola", "es" => "Faisal Fadlelmola", "fr" => "Faisal Fadlelmola"]],
                ["name" => ["en" => "Jean - Baka Domelevo Entfellner", "es" => "Jean - Baka Domelevo Entfellner", "fr" => "Jean - Baka Domelevo Entfellner"]],
                ["name" => ["en" => "Nicola Mulder", "es" => "Nicola Mulder", "fr" => "Nicola Mulder"]],
                ["name" => ["en" => "Oussema Souiai", "es" => "Oussema Souiai", "fr" => "Oussema Souiai"]],
                ["name" => ["en" => "Sumir Panji", "es" => "Sumir Panji", "fr" => "Sumir Panji"]],
                ["name" => ["en" => "Wisdom Akurugu", "es" => "Wisdom Akurugu", "fr" => "Wisdom Akurugu"]],
                ["name" => ["en" => "Faheem Ashraf", "es" => "Faheem Ashraf", "fr" => "Faheem Ashraf"]],
                ["name" => ["en" => "FAO", "es" => "FAO", "fr" => "FAO"]],
                ["name" => ["en" => "Feed the Future", "es" => "Feed the Future", "fr" => "Feed the Future"]],
                ["name" => ["en" => "Felipe Montoya Greenheck", "es" => "Felipe Montoya Greenheck", "fr" => "Felipe Montoya Greenheck"]],
                ["name" => ["en" => "Robert Finlayson", "es" => "Robert Finlayson", "fr" => "Robert Finlayson"]],
                ["name" => ["en" => "Food and Agriculture Organization of the United Nations", "es" => "Food and Agriculture Organization of the United Nations", "fr" => "Food and Agriculture Organization of the United Nations"]],
                ["name" => ["en" => "Frank Tchuwa", "es" => "Frank Tchuwa", "fr" => "Frank Tchuwa"]],
                ["name" => ["en" => "Franklin Mairura", "es" => "Franklin Mairura", "fr" => "Franklin Mairura"]],
                ["name" => ["en" => "Frans Geilfus", "es" => "Frans Geilfus", "fr" => "Frans Geilfus"]],
                ["name" => ["en" => "Fred Rattunde", "es" => "Fred Rattunde", "fr" => "Fred Rattunde"]],
                ["name" => ["en" => "Fredrick Ogutu", "es" => "Fredrick Ogutu", "fr" => "Fredrick Ogutu"]],
                ["name" => ["en" => "Grace Akumu", "es" => "Grace Akumu", "fr" => "Grace Akumu"]],
                ["name" => ["en" => "G . Makumbi", "es" => "G . Makumbi", "fr" => "G . Makumbi"]],
                ["name" => ["en" => "Georges Félix", "es" => "Georges Félix", "fr" => "Georges Félix"]],
                ["name" => ["en" => "Gert Nyberg", "es" => "Gert Nyberg", "fr" => "Gert Nyberg"]],
                ["name" => ["en" => "Gleb Raygorodetsky", "es" => "Gleb Raygorodetsky", "fr" => "Gleb Raygorodetsky"]],
                ["name" => ["en" => "Greg Seymour", "es" => "Greg Seymour", "fr" => "Greg Seymour"]],
                ["name" => ["en" => "Grupo Yanapai", "es" => "Grupo Yanapai", "fr" => "Grupo Yanapai"]],
                ["name" => ["en" => "Gundula Fischer", "es" => "Gundula Fischer", "fr" => "Gundula Fischer"]],
                ["name" => ["en" => "Hafsat Ibrahim", "es" => "Hafsat Ibrahim", "fr" => "Hafsat Ibrahim"]],
                ["name" => ["en" => "Hakeem Ajeigbe", "es" => "Hakeem Ajeigbe", "fr" => "Hakeem Ajeigbe"]],
                ["name" => ["en" => "Hannah Fairbanks", "es" => "Hannah Fairbanks", "fr" => "Hannah Fairbanks"]],
                ["name" => ["en" => "Harry Msere", "es" => "Harry Msere", "fr" => "Harry Msere"]],
                ["name" => ["en" => "Hi Howard", "es" => "Hi Howard", "fr" => "Hi Howard"]],
                ["name" => ["en" => "Ian Fitzpatrick", "es" => "Ian Fitzpatrick", "fr" => "Ian Fitzpatrick"]],
                ["name" => ["en" => "Ian Wilson", "es" => "Ian Wilson", "fr" => "Ian Wilson"]],
                ["name" => ["en" => "Ibbo Moussa", "es" => "Ibbo Moussa", "fr" => "Ibbo Moussa"]],
                ["name" => ["en" => "Ibrahima Sissoko", "es" => "Ibrahima Sissoko", "fr" => "Ibrahima Sissoko"]],
                ["name" => ["en" => "IDEO . org", "es" => "IDEO . org", "fr" => "IDEO . org"]],
                ["name" => ["en" => "Idupulapati Rao", "es" => "Idupulapati Rao", "fr" => "Idupulapati Rao"]],
                ["name" => ["en" => "ILRI", "es" => "ILRI", "fr" => "ILRI"]],
                ["name" => ["en" => "Ingrid Öborn", "es" => "Ingrid Öborn", "fr" => "Ingrid Öborn"]],
                ["name" => ["en" => "International Accountability Project", "es" => "International Accountability Project", "fr" => "International Accountability Project"]],
                ["name" => ["en" => "Ishita Petkar", "es" => "Ishita Petkar", "fr" => "Ishita Petkar"]],
                ["name" => ["en" => "Israel Navarrete", "es" => "Israel Navarrete", "fr" => "Israel Navarrete"]],
                ["name" => ["en" => "J Apil", "es" => "J Apil", "fr" => "J Apil"]],
                ["name" => ["en" => "S Kato", "es" => "S Kato", "fr" => "S Kato"]],
                ["name" => ["en" => "J . I . Mwanje", "es" => "J . I . Mwanje", "fr" => "J . I . Mwanje"]],
                ["name" => ["en" => "Julius Wambete", "es" => "Julius Wambete", "fr" => "Julius Wambete"]],
                ["name" => ["en" => "Juliet Tibagonzeka", "es" => "Juliet Tibagonzeka", "fr" => "Juliet Tibagonzeka"]],
                ["name" => ["en" => "John Muyonga", "es" => "John Muyonga", "fr" => "John Muyonga"]],
                ["name" => ["en" => "Jacques M . Chevalier", "es" => "Jacques M . Chevalier", "fr" => "Jacques M . Chevalier"]],
                ["name" => ["en" => "Jamie A A Gamble", "es" => "Jamie A A Gamble", "fr" => "Jamie A A Gamble"]],
                ["name" => ["en" => "Ramni Jamnadass", "es" => "Ramni Jamnadass", "fr" => "Ramni Jamnadass"]],
                ["name" => ["en" => "Jan Beniest", "es" => "Jan Beniest", "fr" => "Jan Beniest"]],
                ["name" => ["en" => "Jan De Leeuw", "es" => "Jan De Leeuw", "fr" => "Jan De Leeuw"]],
                ["name" => ["en" => "Jane Wei - Skillern", "es" => "Jane Wei - Skillern", "fr" => "Jane Wei - Skillern"]],
                ["name" => ["en" => "Jason Donovan", "es" => "Jason Donovan", "fr" => "Jason Donovan"]],
                ["name" => ["en" => "Jeffery Bentley", "es" => "Jeffery Bentley", "fr" => "Jeffery Bentley"]],
                ["name" => ["en" => "Jere L . Gilles", "es" => "Jere L . Gilles", "fr" => "Jere L . Gilles"]],
                ["name" => ["en" => "Jeroen Groot", "es" => "Jeroen Groot", "fr" => "Jeroen Groot"]],
                ["name" => ["en" => "Jerome Patrick Cruz", "es" => "Jerome Patrick Cruz", "fr" => "Jerome Patrick Cruz"]],
                ["name" => ["en" => "Joel Aiki", "es" => "Joel Aiki", "fr" => "Joel Aiki"]],
                ["name" => ["en" => "John Creswell", "es" => "John Creswell", "fr" => "John Creswell"]],
                ["name" => ["en" => "John Mwebe", "es" => "John Mwebe", "fr" => "John Mwebe"]],
                ["name" => ["en" => "John N . Wairore", "es" => "John N . Wairore", "fr" => "John N . Wairore"]],
                ["name" => ["en" => "John Rowlands", "es" => "John Rowlands", "fr" => "John Rowlands"]],
                ["name" => ["en" => "Johnson Nyasani", "es" => "Johnson Nyasani", "fr" => "Johnson Nyasani"]],
                ["name" => ["en" => "Johnstone O . Tungai", "es" => "Johnstone O . Tungai", "fr" => "Johnstone O . Tungai"]],
                ["name" => ["en" => "Jonas . N . Chianu", "es" => "Jonas . N . Chianu", "fr" => "Jonas . N . Chianu"]],
                ["name" => ["en" => "Jordan Treakle", "es" => "Jordan Treakle", "fr" => "Jordan Treakle"]],
                ["name" => ["en" => "Jorge Suazo", "es" => "Jorge Suazo", "fr" => "Jorge Suazo"]],
                ["name" => ["en" => "Joseph E . Huesing", "es" => "Joseph E . Huesing", "fr" => "Joseph E . Huesing"]],
                ["name" => ["en" => "Josephine Rodgers", "es" => "Josephine Rodgers", "fr" => "Josephine Rodgers"]],
                ["name" => ["en" => "Joshua Ramisch", "es" => "Joshua Ramisch", "fr" => "Joshua Ramisch"]],
                ["name" => ["en" => "Juan Vallejos Arnés", "es" => "Juan Vallejos Arnés", "fr" => "Juan Vallejos Arnés"]],
                ["name" => ["en" => "Julia Wernersson", "es" => "Julia Wernersson", "fr" => "Julia Wernersson"]],
                ["name" => ["en" => "Kaia Ambrose", "es" => "Kaia Ambrose", "fr" => "Kaia Ambrose"]],
                ["name" => ["en" => "Fidelis Kaihura", "es" => "Fidelis Kaihura", "fr" => "Fidelis Kaihura"]],
                ["name" => ["en" => "Kajal Gulati", "es" => "Kajal Gulati", "fr" => "Kajal Gulati"]],
                ["name" => ["en" => "Kate Wellard", "es" => "Kate Wellard", "fr" => "Kate Wellard"]],
                ["name" => ["en" => "Katrien Descheemaeker", "es" => "Katrien Descheemaeker", "fr" => "Katrien Descheemaeker"]],
                ["name" => ["en" => "Ken Giller", "es" => "Ken Giller", "fr" => "Ken Giller"]],
                ["name" => ["en" => "Kevin Richtscheid", "es" => "Kevin Richtscheid", "fr" => "Kevin Richtscheid"]],
                ["name" => ["en" => "Roeland Kindt", "es" => "Roeland Kindt", "fr" => "Roeland Kindt"]],
                ["name" => ["en" => "Kirsten vom Brocke", "es" => "Kirsten vom Brocke", "fr" => "Kirsten vom Brocke"]],
                ["name" => ["en" => "Rodel Lasco", "es" => "Rodel Lasco", "fr" => "Rodel Lasco"]],
                ["name" => ["en" => "Laura Saxer", "es" => "Laura Saxer", "fr" => "Laura Saxer"]],
                ["name" => ["en" => "Lecia Grossman", "es" => "Lecia Grossman", "fr" => "Lecia Grossman"]],
                ["name" => ["en" => "Lisa VeneKlasen", "es" => "Lisa VeneKlasen", "fr" => "Lisa VeneKlasen"]],
                ["name" => ["en" => "Lotje Geutjes", "es" => "Lotje Geutjes", "fr" => "Lotje Geutjes"]],
                ["name" => ["en" => "Lucia Falcinelli", "es" => "Lucia Falcinelli", "fr" => "Lucia Falcinelli"]],
                ["name" => ["en" => "Meine van Noordwijk", "es" => "Meine van Noordwijk", "fr" => "Meine van Noordwijk"]],
                ["name" => ["en" => "Michael Stocking", "es" => "Michael Stocking", "fr" => "Michael Stocking"]],
                ["name" => ["en" => "Madeleine Jönsson", "es" => "Madeleine Jönsson", "fr" => "Madeleine Jönsson"]],
                ["name" => ["en" => "Madelene Ostwald", "es" => "Madelene Ostwald", "fr" => "Madelene Ostwald"]],
                ["name" => ["en" => "Magnus Jirström", "es" => "Magnus Jirström", "fr" => "Magnus Jirström"]],
                ["name" => ["en" => "Mahmoud Elkasabi", "es" => "Mahmoud Elkasabi", "fr" => "Mahmoud Elkasabi"]],
                ["name" => ["en" => "Marc Langlois", "es" => "Marc Langlois", "fr" => "Marc Langlois"]],
                ["name" => ["en" => "Marcella Vrolijks", "es" => "Marcella Vrolijks", "fr" => "Marcella Vrolijks"]],
                ["name" => ["en" => "Kerry Kirwan", "es" => "Kerry Kirwan", "fr" => "Kerry Kirwan"]],
                ["name" => ["en" => "Marco Cinelli", "es" => "Marco Cinelli", "fr" => "Marco Cinelli"]],
                ["name" => ["en" => "Stuart Coles", "es" => "Stuart Coles", "fr" => "Stuart Coles"]],
                ["name" => ["en" => "Margaux Vinez", "es" => "Margaux Vinez", "fr" => "Margaux Vinez"]],
                ["name" => ["en" => "Maria Gabriela Aparentado", "es" => "Maria Gabriela Aparentado", "fr" => "Maria Gabriela Aparentado"]],
                ["name" => ["en" => "Maria Quispe", "es" => "Maria Quispe", "fr" => "Maria Quispe"]],
                ["name" => ["en" => "Marlène Elias", "es" => "Marlène Elias", "fr" => "Marlène Elias"]],
                ["name" => ["en" => "Mary Sanitato", "es" => "Mary Sanitato", "fr" => "Mary Sanitato"]],
                ["name" => ["en" => "Maura Lazarte", "es" => "Maura Lazarte", "fr" => "Maura Lazarte"]],
                ["name" => ["en" => "Mauricio R . Bellon", "es" => "Mauricio R . Bellon", "fr" => "Mauricio R . Bellon"]],
                ["name" => ["en" => "McKnight", "es" => "McKnight", "fr" => "McKnight"]],
                ["name" => ["en" => "Meine van Noordwijk", "es" => "Meine van Noordwijk", "fr" => "Meine van Noordwijk"]],
                ["name" => ["en" => "Mela Chiponda", "es" => "Mela Chiponda", "fr" => "Mela Chiponda"]],
                ["name" => ["en" => "Michael A . Opio", "es" => "Michael A . Opio", "fr" => "Michael A . Opio"]],
                ["name" => ["en" => "Michael O’Sullivan", "es" => "Michael O’Sullivan", "fr" => "Michael O’Sullivan"]],
                ["name" => ["en" => "Michael Quinn Patton", "es" => "Michael Quinn Patton", "fr" => "Michael Quinn Patton"]],
                ["name" => ["en" => "Milton Villca", "es" => "Milton Villca", "fr" => "Milton Villca"]],
                ["name" => ["en" => "Mohammed Y . Said", "es" => "Mohammed Y . Said", "fr" => "Mohammed Y . Said"]],
                ["name" => ["en" => "Molly Reilly", "es" => "Molly Reilly", "fr" => "Molly Reilly"]],
                ["name" => ["en" => "Monica Bautista", "es" => "Monica Bautista", "fr" => "Monica Bautista"]],
                ["name" => ["en" => "Moussa Kanouté", "es" => "Moussa Kanouté", "fr" => "Moussa Kanouté"]],
                ["name" => ["en" => "Mutua A", "es" => "Mutua A", "fr" => "Mutua A"]],
                ["name" => ["en" => "Natasha Blanchet - Cohen", "es" => "Natasha Blanchet - Cohen", "fr" => "Natasha Blanchet - Cohen"]],
                ["name" => ["en" => "Natural Justice", "es" => "Natural Justice", "fr" => "Natural Justice"]],
                ["name" => ["en" => "Neil Rowe Miller", "es" => "Neil Rowe Miller", "fr" => "Neil Rowe Miller"]],
                ["name" => ["en" => "NGI", "es" => "NGI", "fr" => "NGI"]],
                ["name" => ["en" => "Nick Jacobs", "es" => "Nick Jacobs", "fr" => "Nick Jacobs"]],
                ["name" => ["en" => "Nicolas Greliche", "es" => "Nicolas Greliche", "fr" => "Nicolas Greliche"]],
                ["name" => ["en" => "Nora Silver", "es" => "Nora Silver", "fr" => "Nora Silver"]],
                ["name" => ["en" => "Nuru Kipato", "es" => "Nuru Kipato", "fr" => "Nuru Kipato"]],
                ["name" => ["en" => "ONE Campaign", "es" => "ONE Campaign", "fr" => "ONE Campaign"]],
                ["name" => ["en" => "Ortixia Dilts", "es" => "Ortixia Dilts", "fr" => "Ortixia Dilts"]],
                ["name" => ["en" => "Caleb Orwa", "es" => "Caleb Orwa", "fr" => "Caleb Orwa"]],
                ["name" => ["en" => "Ousmane Dembélé", "es" => "Ousmane Dembélé", "fr" => "Ousmane Dembélé"]],
                ["name" => ["en" => "Peter Atekyereza ", "es" => "Peter Atekyereza ", "fr" => "Peter Atekyereza "]],
                ["name" => ["en" => "Pablo Sáenz", "es" => "Pablo Sáenz", "fr" => "Pablo Sáenz"]],
                ["name" => ["en" => "Pablo Tittonell", "es" => "Pablo Tittonell", "fr" => "Pablo Tittonell"]],
                ["name" => ["en" => "Patrick Lavelle", "es" => "Patrick Lavelle", "fr" => "Patrick Lavelle"]],
                ["name" => ["en" => "Paul Kamau Mbugua", "es" => "Paul Kamau Mbugua", "fr" => "Paul Kamau Mbugua"]],
                ["name" => ["en" => "Paul L . Woomer", "es" => "Paul L . Woomer", "fr" => "Paul L . Woomer"]],
                ["name" => ["en" => "Paul Van Mele", "es" => "Paul Van Mele", "fr" => "Paul Van Mele"]],
                ["name" => ["en" => "Pedro Oyarzun", "es" => "Pedro Oyarzun", "fr" => "Pedro Oyarzun"]],
                ["name" => ["en" => "People in Need", "es" => "People in Need", "fr" => "People in Need"]],
                ["name" => ["en" => "Per Knutsson", "es" => "Per Knutsson", "fr" => "Per Knutsson"]],
                ["name" => ["en" => "Peter Minang", "es" => "Peter Minang", "fr" => "Peter Minang"]],
                ["name" => ["en" => "Peter Mwangi", "es" => "Peter Mwangi", "fr" => "Peter Mwangi"]],
                ["name" => ["en" => "Phil Malone", "es" => "Phil Malone", "fr" => "Phil Malone"]],
                ["name" => ["en" => "Philip Dearden", "es" => "Philip Dearden", "fr" => "Philip Dearden"]],
                ["name" => ["en" => "Steven Belmain", "es" => "Steven Belmain", "fr" => "Steven Belmain"]],
                ["name" => ["en" => "Professor S C Pearce", "es" => "Professor S C Pearce", "fr" => "Professor S C Pearce"]],
                ["name" => ["en" => "Putso Nyathi", "es" => "Putso Nyathi", "fr" => "Putso Nyathi"]],
                ["name" => ["en" => "Rainer Krell", "es" => "Rainer Krell", "fr" => "Rainer Krell"]],
                ["name" => ["en" => "Raka Banerjee", "es" => "Raka Banerjee", "fr" => "Raka Banerjee"]],
                ["name" => ["en" => "Ramesh C . Saxena", "es" => "Ramesh C . Saxena", "fr" => "Ramesh C . Saxena"]],
                ["name" => ["en" => "Rebecca Nelson", "es" => "Rebecca Nelson", "fr" => "Rebecca Nelson"]],
                ["name" => ["en" => "Regina Eddy", "es" => "Regina Eddy", "fr" => "Regina Eddy"]],
                ["name" => ["en" => "Regina Wambui", "es" => "Regina Wambui", "fr" => "Regina Wambui"]],
                ["name" => ["en" => "Regional Land Management Unit(RELMA)", "es" => "Regional Land Management Unit(RELMA)", "fr" => "Regional Land Management Unit(RELMA)"]],
                ["name" => ["en" => "Regis Chikowo", "es" => "Regis Chikowo", "fr" => "Regis Chikowo"]],
                ["name" => ["en" => "Rhomis", "es" => "Rhomis", "fr" => "Rhomis"]],
                ["name" => ["en" => "Ric Coe", "es" => "Ric Coe", "fr" => "Ric Coe"]],
                ["name" => ["en" => "Ricardo Proaño", "es" => "Ricardo Proaño", "fr" => "Ricardo Proaño"]],
                ["name" => ["en" => "Robert Mensah", "es" => "Robert Mensah", "fr" => "Robert Mensah"]],
                ["name" => ["en" => "Roger Day", "es" => "Roger Day", "fr" => "Roger Day"]],
                ["name" => ["en" => "Roger Stern", "es" => "Roger Stern", "fr" => "Roger Stern"]],
                ["name" => ["en" => "Rolando Rojas", "es" => "Rolando Rojas", "fr" => "Rolando Rojas"]],
                ["name" => ["en" => "Rolf Sartorius", "es" => "Rolf Sartorius", "fr" => "Rolf Sartorius"]],
                ["name" => ["en" => "Ruth Meinzen - Dick", "es" => "Ruth Meinzen - Dick", "fr" => "Ruth Meinzen - Dick"]],
                ["name" => ["en" => "Sabine Homann - Kee Tui", "es" => "Sabine Homann - Kee Tui", "fr" => "Sabine Homann - Kee Tui"]],
                ["name" => ["en" => "Sabina Alkire", "es" => "Sabina Alkire", "fr" => "Sabina Alkire"]],
                ["name" => ["en" => "Sabine Fründt", "es" => "Sabine Fründt", "fr" => "Sabine Fründt"]],
                ["name" => ["en" => "Sam Dumble", "es" => "Sam Dumble", "fr" => "Sam Dumble"]],
                ["name" => ["en" => "Samuel Guindo", "es" => "Samuel Guindo", "fr" => "Samuel Guindo"]],
                ["name" => ["en" => "Samuel M . ʻOhukaniʻōhiʻa Gon III", "es" => "Samuel M . ʻOhukaniʻōhiʻa Gon III", "fr" => "Samuel M . ʻOhukaniʻōhiʻa Gon III"]],
                ["name" => ["en" => "Sara Namirembe", "es" => "Sara Namirembe", "fr" => "Sara Namirembe"]],
                ["name" => ["en" => "Sara Svanlund", "es" => "Sara Svanlund", "fr" => "Sara Svanlund"]],
                ["name" => ["en" => "Sara Vaca", "es" => "Sara Vaca", "fr" => "Sara Vaca"]],
                ["name" => ["en" => "Sarah Wright", "es" => "Sarah Wright", "fr" => "Sarah Wright"]],
                ["name" => ["en" => "Sarah - Lan Mathez", "es" => "Sarah - Lan Mathez", "fr" => "Sarah - Lan Mathez"]],
                ["name" => ["en" => "Savitri Abeyasekera", "es" => "Savitri Abeyasekera", "fr" => "Savitri Abeyasekera"]],
                ["name" => ["en" => "Sebastian Steinmüller", "es" => "Sebastian Steinmüller", "fr" => "Sebastian Steinmüller"]],
                ["name" => ["en" => "Sharlene Hesse - Biber", "es" => "Sharlene Hesse - Biber", "fr" => "Sharlene Hesse - Biber"]],
                ["name" => ["en" => "Shiphar Mulumba", "es" => "Shiphar Mulumba", "fr" => "Shiphar Mulumba"]],
                ["name" => ["en" => "Sida Studies in Evaluation", "es" => "Sida Studies in Evaluation", "fr" => "Sida Studies in Evaluation"]],
                ["name" => ["en" => "Sidi Touré", "es" => "Sidi Touré", "fr" => "Sidi Touré"]],
                ["name" => ["en" => "Sieg Snapp", "es" => "Sieg Snapp", "fr" => "Sieg Snapp"]],
                ["name" => ["en" => "Elisabeth Simelton", "es" => "Elisabeth Simelton", "fr" => "Elisabeth Simelton"]],
                ["name" => ["en" => "Simon Wittich", "es" => "Simon Wittich", "fr" => "Simon Wittich"]],
                ["name" => ["en" => "Tony Simons", "es" => "Tony Simons", "fr" => "Tony Simons"]],
                ["name" => ["en" => "Sonia Laura", "es" => "Sonia Laura", "fr" => "Sonia Laura"]],
                ["name" => ["en" => "Sonja Siart", "es" => "Sonja Siart", "fr" => "Sonja Siart"]],
                ["name" => ["en" => "Sophie Grig", "es" => "Sophie Grig", "fr" => "Sophie Grig"]],
                ["name" => ["en" => "Soroush Parsa", "es" => "Soroush Parsa", "fr" => "Soroush Parsa"]],
                ["name" => ["en" => "Statistical Services Centre", "es" => "Statistical Services Centre", "fr" => "Statistical Services Centre"]],
                ["name" => ["en" => "Stats4SD", "es" => "Stats4SD", "fr" => "Stats4SD"]],
                ["name" => ["en" => "Stella Grace Lutalo", "es" => "Stella Grace Lutalo", "fr" => "Stella Grace Lutalo"]],
                ["name" => ["en" => "Stéphanie Alvarez", "es" => "Stéphanie Alvarez", "fr" => "Stéphanie Alvarez"]],
                ["name" => ["en" => "Stephanie Williamson", "es" => "Stephanie Williamson", "fr" => "Stephanie Williamson"]],
                ["name" => ["en" => "Stephen Mureithi", "es" => "Stephen Mureithi", "fr" => "Stephen Mureithi"]],
                ["name" => ["en" => "Steve Jones", "es" => "Steve Jones", "fr" => "Steve Jones"]],
                ["name" => ["en" => "Steven Franzel", "es" => "Steven Franzel", "fr" => "Steven Franzel"]],
                ["name" => ["en" => "Steven Fonte", "es" => "Steven Fonte", "fr" => "Steven Fonte"]],
                ["name" => ["en" => "Steven Vanek", "es" => "Steven Vanek", "fr" => "Steven Vanek"]],
                ["name" => ["en" => "Sukhgerel Dugersuren", "es" => "Sukhgerel Dugersuren", "fr" => "Sukhgerel Dugersuren"]],
                ["name" => ["en" => "Takuji W . Tsusaka", "es" => "Takuji W . Tsusaka", "fr" => "Takuji W . Tsusaka"]],
                ["name" => ["en" => "Tessa Minter", "es" => "Tessa Minter", "fr" => "Tessa Minter"]],
                ["name" => ["en" => "The Alliance for Food Sovereignty in Africa(AFSA)", "es" => "The Alliance for Food Sovereignty in Africa(AFSA)", "fr" => "The Alliance for Food Sovereignty in Africa(AFSA)"]],
                ["name" => ["en" => "The World Bank", "es" => "The World Bank", "fr" => "The World Bank"]],
                ["name" => ["en" => "Thomas Headland", "es" => "Thomas Headland", "fr" => "Thomas Headland"]],
                ["name" => ["en" => "Tirso Gonzales", "es" => "Tirso Gonzales", "fr" => "Tirso Gonzales"]],
                ["name" => ["en" => "Tom van Mourik", "es" => "Tom van Mourik", "fr" => "Tom van Mourik"]],
                ["name" => ["en" => "Tom Weerachat", "es" => "Tom Weerachat", "fr" => "Tom Weerachat"]],
                ["name" => ["en" => "Tony Rinaudo", "es" => "Tony Rinaudo", "fr" => "Tony Rinaudo"]],
                ["name" => ["en" => "Tufts University", "es" => "Tufts University", "fr" => "Tufts University"]],
                ["name" => ["en" => "University of Reading", "es" => "University of Reading", "fr" => "University of Reading"]],
                ["name" => ["en" => "USAID", "es" => "USAID", "fr" => "USAID"]],
                ["name" => ["en" => "Valerie Miller", "es" => "Valerie Miller", "fr" => "Valerie Miller"]],
                ["name" => ["en" => "Vera Karmebäck", "es" => "Vera Karmebäck", "fr" => "Vera Karmebäck"]],
                ["name" => ["en" => "Virginia Peschke", "es" => "Virginia Peschke", "fr" => "Virginia Peschke"]],
                ["name" => ["en" => "Wilson Ronno", "es" => "Wilson Ronno", "fr" => "Wilson Ronno"]],
                ["name" => ["en" => "Wim Paas", "es" => "Wim Paas", "fr" => "Wim Paas"]],
                ["name" => ["en" => "World Agroforestry Centre", "es" => "World Agroforestry Centre", "fr" => "World Agroforestry Centre"]],
                ["name" => ["en" => "World Neighbors", "es" => "World Neighbors", "fr" => "World Neighbors"]],
                ["name" => ["en" => "World Vision Australia", "es" => "World Vision Australia", "fr" => "World Vision Australia"]],
                ["name" => ["en" => "Bingbing Zhou", "es" => "Bingbing Zhou", "fr" => "Bingbing Zhou"]],
                ["name" => ["en" => "Ignacio C . Fernandez", "es" => "Ignacio C . Fernandez", "fr" => "Ignacio C . Fernandez"]],
                ["name" => ["en" => "Jianguo Wu", "es" => "Jianguo Wu", "fr" => "Jianguo Wu"]],
                ["name" => ["en" => "Jie Guo", "es" => "Jie Guo", "fr" => "Jie Guo"]],
                ["name" => ["en" => "Maxwell Wilson", "es" => "Maxwell Wilson", "fr" => "Maxwell Wilson"]],
                ["name" => ["en" => "Xiaoyu Gan", "es" => "Xiaoyu Gan", "fr" => "Xiaoyu Gan"]],
                ["name" => ["en" => "Yuanyuan Zhao", "es" => "Yuanyuan Zhao", "fr" => "Yuanyuan Zhao"]],
                ["name" => ["en" => "Yvonne Vizina", "es" => "Yvonne Vizina", "fr" => "Yvonne Vizina"]],
                ["name" => ["en" => "Jacky Knowles"]],
                ["name" => ["en" => "Greens\/EFA"]],
                ["name" => ["en" => "Colin Anderson"]],
                ["name" => ["en" => "Csilla Kiss"]],
                ["name" => ["en" => "Michel Pimbert"]],
                ["name" => ["en" => "Centre for Agriculture and Bioscience International"]],
                ["name" => ["en" => "Luke Owen"]],
                ["name" => ["en" => "Paola Guzman"]],
                ["name" => ["en" => "Moya Kneafsey"]],
                ["name" => ["en" => "Chelsea Marshall"]],
                ["name" => ["en" => "Clare Horrell"]],
                ["name" => ["en" => "Jane Sweetman"]],
                ["name" => ["en" => "Wezi Mhango"]],
                ["name" => ["en" => "Edgar Olivera"]],
                ["name" => ["en" => "Lalisa Duguma"]],
                ["name" => ["en" => "Anthony Kimaro"]],
                ["name" => ["en" => "Robert Otsyina"]],
                ["name" => ["en" => "Mathew Mpanda"]],
                ["name" => ["en" => "Gerard Cornelissen"]],
                ["name" => ["en" => "Victor Shitumbanuma"]],
                ["name" => ["en" => "Vegard Martinsen"]],
                ["name" => ["en" => "Krystyna Swiderska"]],
                ["name" => ["en" => "Alejandro Argumedo"]],
                ["name" => ["en" => "Yiching Song"]],
                ["name" => ["en" => "Jingsong Li"]],
                ["name" => ["en" => "Ruchi Pant"]],
                ["name" => ["en" => "Heraclio Herrera"]],
                ["name" => ["en" => "Doris Mutta"]],
                ["name" => ["en" => "Peter Munyi"]],
                ["name" => ["en" => "S Vedavathy"]],
                ["name" => ["en" => "Eric van Holm"]],
                ["name" => ["en" => "Bana Salameh"]],
                ["name" => ["en" => "Malek Batal"]],
                ["name" => ["en" => "Samuel Nderitu"]],
                ["name" => ["en" => "Jo Smith"]],
                ["name" => ["en" => "Organic Research Centre"]],
                ["name" => ["en" => "Ulrich Schmutz"]],
                ["name" => ["en" => "PROINPA FOUNDATION"]],
                ["name" => ["en" => "Francesco Braga"]],
                ["name" => ["en" => "Fritz H\u00e4ni"]],
                ["name" => ["en" => "Andreas St\u00e4mpfli"]],
                ["name" => ["en" => "Thomas Keller"]],
                ["name" => ["en" => "Matthew Fischer"]],
                ["name" => ["en" => "Hans Porsche"]],
                ["name" => ["en" => "Jane Poole"]],
                ["name" => ["en" => "David Priest"]],
                ["name" => ["en" => "FIPS"]],
                ["name" => ["en" => "Agroecology Support Team(AES)"]],
                ["name" => ["en" => "Gabriela Bucini"]],
                ["name" => ["en" => "Robert Burn"]],
                ["name" => ["en" => "dave priest"]],
                ["name" => ["en" => "Ligia Paina"]],
                ["name" => ["en" => "Alliance for Health Policy and Systems Research"]],
                ["name" => ["en" => "IDEMS International"]],
                ["name" => ["en" => "Kenneth Frank"]],
                ["name" => ["en" => "Ciara McHugh"]],
                ["name" => ["en" => "Josue Job Huanay Quispe"]],
                ["name" => ["en" => "Kaufmann, J . et al"]],
                ["name" => ["en" => "Paul P Biemer"]],
                ["name" => ["en" => "Lucie Hazelgrove - Planel"]],
                ["name" => ["en" => "Roger Kabor\u00e9"]],
                ["name" => ["en" => "Romina De Angelis"]],
                ["name" => ["en" => "Elizabeth Dick"]],
                ["name" => ["en" => "Cornelia Butler Flora"]],
                ["name" => ["en" => "IOM"]],
                ["name" => ["en" => "Rodrigo Paz Y"]],
                ["name" => ["en" => "Peter Gubbels"]],
                ["name" => ["en" => "Jane Maland Cady"]],
                ["name" => ["en" => "Marah Moore"]],
                ["name" => ["en" => "Bettina Haussmann"]],
                ["name" => ["en" => "Mary Richardson"]],
                ["name" => ["en" => "Batamaka Som\u00e9"]],
                ["name" => ["en" => "Beth Medvecky"]],
                ["name" => ["en" => "Daniel Laughlin"]],
            ]);
        }


    }
}
